apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: argocd-complementary-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
